export enum SocketCommand {
  StartTime = 'startTime',
  StopTime = 'stopTime',
  CorrectAnswer = 'correctAnswer',
  NextQuestion = 'nextQuestion',
  SetCurrentQuestion = 'setCurrentQuestion',
  ShowAllAnswers = 'showAllAnswers',
  NextImage = 'nextImage',
  SetView = 'setView',
  PreviousRound = 'previousRound',
  NextRound = 'nextRound',
  NextFinale = 'nextFinale',
  NextStartingPlayer = 'nextStartingPlayer',
  NextPlayerToComplete = 'nextPlayerToComplete',
  SetPlayerName = 'setPlayerName',
  SetPlayerTime = 'setPlayerTime',
  SetPlayerCameraLink = 'setPlayerCameraLink',
  ShowJury = 'showJury',
  HideJury = 'hideJury',
  ToggleJury = 'toggleJury',
  PlayVideo = 'playVideo',
  playApplause = 'playApplause',
  StartIntroLoop = 'startIntroLoop',
  StopIntroLoop = 'stopIntroLoop',
  PlayOpening = 'playOpening',
  FocusPlayer = 'focusPlayer',
  SetPauseTargetTime = 'SetPauseTargetTime',
}
